#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

db_ready() {
python << END
import sys
from sqlalchemy import create_engine
import os

url = os.environ['DATABASE_URL']

try:
    engine = create_engine(url,)
except Exception as e:
    print(e)
    sys.exit(-1)
sys.exit(0)

END
}
until db_ready; do
  >&2 echo 'Waiting for database to become available...'
  sleep 1
done
>&2 echo 'Database is available'

exec "$@"