#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

pip install debugpy -t /tmp
python /tmp/debugpy --listen 0.0.0.0:5678 -m uvicorn main:app --reload --reload-dir project --host 0.0.0.0

# uvicorn main:app --reload --reload-dir project --host 0.0.0.0
