"""empty message

Revision ID: 06fded13151b
Revises: a6e3b59e3766
Create Date: 2023-09-08 18:26:26.714151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06fded13151b'
down_revision = 'a6e3b59e3766'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
