"""empty message

Revision ID: 325b44588dfb
Revises: d3e19f7a792b
Create Date: 2023-04-21 20:10:02.971940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325b44588dfb'
down_revision = 'd3e19f7a792b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
