"""init

Revision ID: 4147dc9848ab
Revises: 
Create Date: 2023-04-18 23:55:59.825789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4147dc9848ab"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("process_time", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_id"), "job", ["id"], unique=False)
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("txt", sa.String(), nullable=True),
        sa.Column("impaakt_score", sa.Float(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_id"), "source", ["id"], unique=False)
    op.create_table(
        "entity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity", sa.String(), nullable=True),
        sa.Column("count", sa.String(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entity_id"), "entity", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_entity_id"), table_name="entity")
    op.drop_table("entity")
    op.drop_index(op.f("ix_source_id"), table_name="source")
    op.drop_table("source")
    op.drop_index(op.f("ix_job_id"), table_name="job")
    op.drop_table("job")
    # ### end Alembic commands ###
