"""empty message

Revision ID: 53ff5340c61c
Revises: e52bd0cf444c
Create Date: 2023-04-19 21:17:19.742672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ff5340c61c'
down_revision = 'e52bd0cf444c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
