"""empty message

Revision ID: 6181f221a1f6
Revises: 06fded13151b
Create Date: 2023-10-05 14:52:46.359094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6181f221a1f6'
down_revision = '06fded13151b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
