"""empty message

Revision ID: 7663980e231b
Revises: dfa5d47aa56d
Create Date: 2023-04-21 20:22:11.456157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7663980e231b'
down_revision = 'dfa5d47aa56d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity', 'count')
    # ### end Alembic commands ###
