"""job options rev

Revision ID: 8bf964d395f5
Revises: dac1c021150f
Create Date: 2023-04-19 15:46:30.532211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf964d395f5'
down_revision = 'dac1c021150f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('impaakt_ranking', sa.Boolean(), nullable=True))
    op.drop_column('job', 'implaakt_classification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('implaakt_classification', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('job', 'impaakt_ranking')
    # ### end Alembic commands ###
