"""empty message

Revision ID: 8c1e49f06b40
Revises: 6181f221a1f6
Create Date: 2023-10-05 14:53:12.806044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1e49f06b40'
down_revision = '6181f221a1f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('concept_source', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('concept_id', sa.String(), nullable=True),
    sa.Column('concept_form', sa.String(), nullable=True),
    sa.Column('prefered_term', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('start_index', sa.Integer(), nullable=True),
    sa.Column('end_index', sa.Integer(), nullable=True),
    sa.Column('concept_length', sa.Integer(), nullable=True),
    sa.Column('sentence_number', sa.String(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_id'), 'annotation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_id'), table_name='annotation')
    op.drop_table('annotation')
    # ### end Alembic commands ###
