"""empty message

Revision ID: 96e78a33df8f
Revises: 8c1e49f06b40
Create Date: 2023-10-06 09:56:25.338378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e78a33df8f'
down_revision = '8c1e49f06b40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_annotation_id', table_name='annotation')
    op.drop_table('annotation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('concept_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('concept_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('concept_form', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prefered_term', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nature', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('concept_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sentence_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name='annotation_article_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='annotation_pkey')
    )
    op.create_index('ix_annotation_id', 'annotation', ['id'], unique=False)
    # ### end Alembic commands ###
