"""empty message

Revision ID: a6e3b59e3766
Revises: 
Create Date: 2023-07-30 15:49:58.964346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e3b59e3766'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('use_fulltext', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('process_time', sa.Float(), nullable=True),
    sa.Column('job_created_at', sa.DateTime(), nullable=True),
    sa.Column('process_start_at', sa.DateTime(), nullable=True),
    sa.Column('process_end_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_id'), 'job', ['id'], unique=False)
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pmid', sa.Integer(), nullable=False),
    sa.Column('pmcid', sa.String(), nullable=True),
    sa.Column('text_source', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_id'), 'article', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_id'), table_name='article')
    op.drop_table('article')
    op.drop_index(op.f('ix_job_id'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
