"""company

Revision ID: b44bf70518ba
Revises: 8bf964d395f5
Create Date: 2023-04-19 20:53:11.619333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44bf70518ba'
down_revision = '8bf964d395f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
