"""empty message

Revision ID: d3e19f7a792b
Revises: dadc546a31b7
Create Date: 2023-04-21 13:09:23.331057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e19f7a792b'
down_revision = 'dadc546a31b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('job_created_at', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('process_start_at', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('process_end_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'process_end_at')
    op.drop_column('job', 'process_start_at')
    op.drop_column('job', 'job_created_at')
    # ### end Alembic commands ###
