"""job options revision

Revision ID: dac1c021150f
Revises: ff3e22784118
Create Date: 2023-04-19 11:17:18.161683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac1c021150f'
down_revision = 'ff3e22784118'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('implaakt_classification', sa.Boolean(), nullable=True))
    op.add_column('job', sa.Column('named_entity_recognition', sa.Boolean(), nullable=True))
    op.add_column('job', sa.Column('company_classification', sa.Boolean(), nullable=True))
    op.drop_column('job', 'NER_company')
    op.drop_column('job', 'impaakt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('impaakt', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('job', sa.Column('NER_company', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('job', 'company_classification')
    op.drop_column('job', 'named_entity_recognition')
    op.drop_column('job', 'implaakt_classification')
    # ### end Alembic commands ###
