"""empty message

Revision ID: dfa5d47aa56d
Revises: 325b44588dfb
Create Date: 2023-04-21 20:16:51.202705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa5d47aa56d'
down_revision = '325b44588dfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('count', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
