"""company

Revision ID: e52bd0cf444c
Revises: b44bf70518ba
Create Date: 2023-04-19 20:56:04.057771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52bd0cf444c'
down_revision = 'b44bf70518ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
