"""empty message

Revision ID: efc03549fe1a
Revises: 96e78a33df8f
Create Date: 2023-10-06 10:05:10.727831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc03549fe1a'
down_revision = '96e78a33df8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('entrez_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'entrez_date')
    # ### end Alembic commands ###
