"""text

Revision ID: f5eb1d54986d
Revises: 4147dc9848ab
Create Date: 2023-04-19 10:06:57.776759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5eb1d54986d'
down_revision = '4147dc9848ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('text', sa.String(), nullable=True))
    op.drop_column('source', 'txt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('txt', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('source', 'text')
    # ### end Alembic commands ###
