"""job options

Revision ID: ff3e22784118
Revises: f5eb1d54986d
Create Date: 2023-04-19 10:39:40.867593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3e22784118'
down_revision = 'f5eb1d54986d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('impaakt', sa.Boolean(), nullable=True))
    op.add_column('job', sa.Column('NER_company', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'NER_company')
    op.drop_column('job', 'impaakt')
    # ### end Alembic commands ###
